In [2]:
import pandas as pd

# Series

In [3]:
marks = pd.Series([85, 90, 76, 95])

print(marks)

0    85
1    90
2    76
3    95
dtype: int64

In [4]:
print(marks[1])

90

# DataFrame

In [6]:
data = {
    "Name": ["Rahul", "Anu", "Raj"],
    "Age": [20, 21, 19],
    "Salary": [50000, 60000, 45000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Salary
0  Rahul   20   50000
1    Anu   21   60000
2    Raj   19   45000

# CREATING DATAFRAME

In [14]:
# From Dictionary
data = {
    "Name":["Hazal","Ali"],
    "Age":[20,19]
}
df = pd.DataFrame(data)

In [15]:
df

    Name  Age
0  Hazal   20
1    Ali   19

In [16]:
# From List
data = [
    ["Hazal",20],
    ["Ali",19]
]
df = pd.DataFrame(data,columns=["Name","Age"])
df

    Name  Age
0  Hazal   20
1    Ali   19

In [ ]:
# df = pd.read_csv(" ")

In [18]:
data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    "Name": [
        "Aarav", "Diya", "Rohan", "Ananya", "Karan",
        "Meera", "Aditya", "Sneha", "Rahul", "Priya"
    ],
    
    "Age": [19, 20, 19, 20, 21, 19, 20, 21, 19, 20],
    
    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],
    
    "Department": [
        "AIML", "CSE", "AIML", "ISE", "CSE",
        "AIML", "ISE", "CSE", "AIML", "ISE"
    ],
    
    "Math": [85, 78, 92, 67, 74, 88, 59, 95, 81, 73],
    
    "Python": [90, 85, 95, 72, 68, 91, 65, 93, 79, 77],
    
    "AI": [88, 82, 94, 70, 76, 90, 62, 97, 85, 71],
    
    "Attendance": [92, 88, 96, 75, 82, 94, 70, 98, 89, 80],
    
    "Projects": [3, 2, 4, 1, 2, 3, 1, 5, 2, 2],
    
    "Placement": [
        "Yes", "Yes", "Yes", "No", "No",
        "Yes", "No", "Yes", "Yes", "No"
    ]
}
df = pd.DataFrame(data)

In [21]:
df

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Projects,Placement
0,101,Aarav,19,Male,AIML,85,90,88,92,3,Yes
1,102,Diya,20,Female,CSE,78,85,82,88,2,Yes
2,103,Rohan,19,Male,AIML,92,95,94,96,4,Yes
3,104,Ananya,20,Female,ISE,67,72,70,75,1,No
4,105,Karan,21,Male,CSE,74,68,76,82,2,No
5,106,Meera,19,Female,AIML,88,91,90,94,3,Yes
6,107,Aditya,20,Male,ISE,59,65,62,70,1,No
7,108,Sneha,21,Female,CSE,95,93,97,98,5,Yes
8,109,Rahul,19,Male,AIML,81,79,85,89,2,Yes
9,110,Priya,20,Female,ISE,73,77,71,80,2,No

In [22]:
df.head()

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Projects,Placement
0,101,Aarav,19,Male,AIML,85,90,88,92,3,Yes
1,102,Diya,20,Female,CSE,78,85,82,88,2,Yes
2,103,Rohan,19,Male,AIML,92,95,94,96,4,Yes
3,104,Ananya,20,Female,ISE,67,72,70,75,1,No
4,105,Karan,21,Male,CSE,74,68,76,82,2,No

In [23]:
df.tail()

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Projects,Placement
5,106,Meera,19,Female,AIML,88,91,90,94,3,Yes
6,107,Aditya,20,Male,ISE,59,65,62,70,1,No
7,108,Sneha,21,Female,CSE,95,93,97,98,5,Yes
8,109,Rahul,19,Male,AIML,81,79,85,89,2,Yes
9,110,Priya,20,Female,ISE,73,77,71,80,2,No

In [33]:
df.shape

(10, 11)

In [34]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Math', 'Python',
       'AI', 'Attendance', 'Projects', 'Placement'],
      dtype='object')

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Gender      10 non-null     object
 4   Department  10 non-null     object
 5   Math        10 non-null     int64
 6   Python      10 non-null     int64
 7   AI          10 non-null     int64
 8   Attendance  10 non-null     int64
 9   Projects    10 non-null     int64
 10  Placement   10 non-null     object
dtypes: int64(7), object(4)
memory usage: 1008.0+ bytes

In [36]:
df.describe()

,Student_ID,Age,Math,Python,AI,Attendance,Projects
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,105.50000,19.800000,79.200000,81.500000,81.500000,86.400000,2.500000
std,3.02765,0.788811,11.311744,10.855106,11.433382,9.335714,1.269296
min,101.00000,19.000000,59.000000,65.000000,62.000000,70.000000,1.000000
25%,103.25000,19.000000,73.250000,73.250000,72.250000,80.500000,2.000000
50%,105.50000,20.000000,79.500000,82.000000,83.500000,88.500000,2.000000
75%,107.75000,20.000000,87.250000,90.750000,89.500000,93.500000,3.000000
max,110.00000,21.000000,95.000000,95.000000,97.000000,98.000000,5.000000

In [37]:
df["Age"] # returns a series

0    19
1    20
2    19
3    20
4    21
5    19
6    20
7    21
8    19
9    20
Name: Age, dtype: int64

In [39]:
df[["Age","Math"]] # return a dataframe

   Age  Math
0   19    85
1   20    78
2   19    92
3   20    67
4   21    74
5   19    88
6   20    59
7   21    95
8   19    81
9   20    73

In [41]:
# Selecting Rows
# Location by label
df.loc[0]

Student_ID      101
Name          Aarav
Age              19
Gender         Male
Department     AIML
Math             85
Python           90
AI               88
Attendance       92
Projects          3
Placement       Yes
Name: 0, dtype: object

In [42]:
df.loc[0:2] # 0 to 2 both are included

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Projects,Placement
0,101,Aarav,19,Male,AIML,85,90,88,92,3,Yes
1,102,Diya,20,Female,CSE,78,85,82,88,2,Yes
2,103,Rohan,19,Male,AIML,92,95,94,96,4,Yes

In [43]:
df.loc[0:2,["Math","Age"]]

   Math  Age
0    85   19
1    78   20
2    92   19

In [ ]:
# iloc location by integer position
# follows normal python slicing so 3 is excluded

In [46]:
df.iloc[0:3]

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Projects,Placement
0,101,Aarav,19,Male,AIML,85,90,88,92,3,Yes
1,102,Diya,20,Female,CSE,78,85,82,88,2,Yes
2,103,Rohan,19,Male,AIML,92,95,94,96,4,Yes

In [47]:
df.iloc[0,3]

'Male'

In [48]:
df.iloc[1,8]

88

In [49]:
df[df["Age"]>20]

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Projects,Placement
4,105,Karan,21,Male,CSE,74,68,76,82,2,No
7,108,Sneha,21,Female,CSE,95,93,97,98,5,Yes

In [53]:
df[(df["Age"] > 20) & (df["Math"] > 80)]

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Projects,Placement
7,108,Sneha,21,Female,CSE,95,93,97,98,5,Yes

In [58]:
df.sort_values("Age",ascending = True) # sort in ascending

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Projects,Placement
0,101,Aarav,19,Male,AIML,85,90,88,92,3,Yes
2,103,Rohan,19,Male,AIML,92,95,94,96,4,Yes
5,106,Meera,19,Female,AIML,88,91,90,94,3,Yes
8,109,Rahul,19,Male,AIML,81,79,85,89,2,Yes
1,102,Diya,20,Female,CSE,78,85,82,88,2,Yes
3,104,Ananya,20,Female,ISE,67,72,70,75,1,No
6,107,Aditya,20,Male,ISE,59,65,62,70,1,No
9,110,Priya,20,Female,ISE,73,77,71,80,2,No
4,105,Karan,21,Male,CSE,74,68,76,82,2,No
7,108,Sneha,21,Female,CSE,95,93,97,98,5,Yes

In [59]:
df.sort_values("Age",ascending = False) # sort in descending

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Projects,Placement
4,105,Karan,21,Male,CSE,74,68,76,82,2,No
7,108,Sneha,21,Female,CSE,95,93,97,98,5,Yes
1,102,Diya,20,Female,CSE,78,85,82,88,2,Yes
3,104,Ananya,20,Female,ISE,67,72,70,75,1,No
6,107,Aditya,20,Male,ISE,59,65,62,70,1,No
9,110,Priya,20,Female,ISE,73,77,71,80,2,No
0,101,Aarav,19,Male,AIML,85,90,88,92,3,Yes
2,103,Rohan,19,Male,AIML,92,95,94,96,4,Yes
5,106,Meera,19,Female,AIML,88,91,90,94,3,Yes
8,109,Rahul,19,Male,AIML,81,79,85,89,2,Yes

In [60]:
df["Age"] = df["Age"] + 1

In [61]:
df

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Projects,Placement
0,101,Aarav,20,Male,AIML,85,90,88,92,3,Yes
1,102,Diya,21,Female,CSE,78,85,82,88,2,Yes
2,103,Rohan,20,Male,AIML,92,95,94,96,4,Yes
3,104,Ananya,21,Female,ISE,67,72,70,75,1,No
4,105,Karan,22,Male,CSE,74,68,76,82,2,No
5,106,Meera,20,Female,AIML,88,91,90,94,3,Yes
6,107,Aditya,21,Male,ISE,59,65,62,70,1,No
7,108,Sneha,22,Female,CSE,95,93,97,98,5,Yes
8,109,Rahul,20,Male,AIML,81,79,85,89,2,Yes
9,110,Priya,21,Female,ISE,73,77,71,80,2,No

In [62]:
 df.drop("Projects",axis =1,inplace=True) # inplace=True-->permanently delete

In [63]:
df

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Placement
0,101,Aarav,20,Male,AIML,85,90,88,92,Yes
1,102,Diya,21,Female,CSE,78,85,82,88,Yes
2,103,Rohan,20,Male,AIML,92,95,94,96,Yes
3,104,Ananya,21,Female,ISE,67,72,70,75,No
4,105,Karan,22,Male,CSE,74,68,76,82,No
5,106,Meera,20,Female,AIML,88,91,90,94,Yes
6,107,Aditya,21,Male,ISE,59,65,62,70,No
7,108,Sneha,22,Female,CSE,95,93,97,98,Yes
8,109,Rahul,20,Male,AIML,81,79,85,89,Yes
9,110,Priya,21,Female,ISE,73,77,71,80,No

In [65]:
# df.isnull()
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
Department    0
Math          0
Python        0
AI            0
Attendance    0
Placement     0
dtype: int64

In [66]:
df.dropna() #Removes rows containing missing values

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Placement
0,101,Aarav,20,Male,AIML,85,90,88,92,Yes
1,102,Diya,21,Female,CSE,78,85,82,88,Yes
2,103,Rohan,20,Male,AIML,92,95,94,96,Yes
3,104,Ananya,21,Female,ISE,67,72,70,75,No
4,105,Karan,22,Male,CSE,74,68,76,82,No
5,106,Meera,20,Female,AIML,88,91,90,94,Yes
6,107,Aditya,21,Male,ISE,59,65,62,70,No
7,108,Sneha,22,Female,CSE,95,93,97,98,Yes
8,109,Rahul,20,Male,AIML,81,79,85,89,Yes
9,110,Priya,21,Female,ISE,73,77,71,80,No

In [ ]:
# df["Age"].fillna(20)
# df["Age"].fillna(df["Age"].mean())  ---> IMPUTATION
# Missing Age
     # ↓
# calculate average Age
     # ↓
# put average in missing location

In [67]:
df.duplicated().sum()

0

In [68]:
df.drop_duplicates()

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Placement
0,101,Aarav,20,Male,AIML,85,90,88,92,Yes
1,102,Diya,21,Female,CSE,78,85,82,88,Yes
2,103,Rohan,20,Male,AIML,92,95,94,96,Yes
3,104,Ananya,21,Female,ISE,67,72,70,75,No
4,105,Karan,22,Male,CSE,74,68,76,82,No
5,106,Meera,20,Female,AIML,88,91,90,94,Yes
6,107,Aditya,21,Male,ISE,59,65,62,70,No
7,108,Sneha,22,Female,CSE,95,93,97,98,Yes
8,109,Rahul,20,Male,AIML,81,79,85,89,Yes
9,110,Priya,21,Female,ISE,73,77,71,80,No

In [69]:
df.dtypes

Student_ID     int64
Name          object
Age            int64
Gender        object
Department    object
Math           int64
Python         int64
AI             int64
Attendance     int64
Placement     object
dtype: object

In [71]:
df["Age"] = df["Age"].astype(float)

In [72]:
df

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Placement
0,101,Aarav,20.0,Male,AIML,85,90,88,92,Yes
1,102,Diya,21.0,Female,CSE,78,85,82,88,Yes
2,103,Rohan,20.0,Male,AIML,92,95,94,96,Yes
3,104,Ananya,21.0,Female,ISE,67,72,70,75,No
4,105,Karan,22.0,Male,CSE,74,68,76,82,No
5,106,Meera,20.0,Female,AIML,88,91,90,94,Yes
6,107,Aditya,21.0,Male,ISE,59,65,62,70,No
7,108,Sneha,22.0,Female,CSE,95,93,97,98,Yes
8,109,Rahul,20.0,Male,AIML,81,79,85,89,Yes
9,110,Priya,21.0,Female,ISE,73,77,71,80,No

In [75]:
df["Age"] = pd.to_numeric(df["Age"]) #Changing Data Type

In [76]:
df

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Placement
0,101,Aarav,20.0,Male,AIML,85,90,88,92,Yes
1,102,Diya,21.0,Female,CSE,78,85,82,88,Yes
2,103,Rohan,20.0,Male,AIML,92,95,94,96,Yes
3,104,Ananya,21.0,Female,ISE,67,72,70,75,No
4,105,Karan,22.0,Male,CSE,74,68,76,82,No
5,106,Meera,20.0,Female,AIML,88,91,90,94,Yes
6,107,Aditya,21.0,Male,ISE,59,65,62,70,No
7,108,Sneha,22.0,Female,CSE,95,93,97,98,Yes
8,109,Rahul,20.0,Male,AIML,81,79,85,89,Yes
9,110,Priya,21.0,Female,ISE,73,77,71,80,No

In [77]:
df["Name"] = df["Name"].str.strip()

In [78]:
df

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Placement
0,101,Aarav,20.0,Male,AIML,85,90,88,92,Yes
1,102,Diya,21.0,Female,CSE,78,85,82,88,Yes
2,103,Rohan,20.0,Male,AIML,92,95,94,96,Yes
3,104,Ananya,21.0,Female,ISE,67,72,70,75,No
4,105,Karan,22.0,Male,CSE,74,68,76,82,No
5,106,Meera,20.0,Female,AIML,88,91,90,94,Yes
6,107,Aditya,21.0,Male,ISE,59,65,62,70,No
7,108,Sneha,22.0,Female,CSE,95,93,97,98,Yes
8,109,Rahul,20.0,Male,AIML,81,79,85,89,Yes
9,110,Priya,21.0,Female,ISE,73,77,71,80,No

In [79]:
df["Name"] = df["Name"].str.lower()
df.head()

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Placement
0,101,aarav,20.0,Male,AIML,85,90,88,92,Yes
1,102,diya,21.0,Female,CSE,78,85,82,88,Yes
2,103,rohan,20.0,Male,AIML,92,95,94,96,Yes
3,104,ananya,21.0,Female,ISE,67,72,70,75,No
4,105,karan,22.0,Male,CSE,74,68,76,82,No

In [80]:
df["Name"] = df["Name"].str.upper()
df.head()

,Student_ID,Name,Age,Gender,Department,Math,Python,AI,Attendance,Placement
0,101,AARAV,20.0,Male,AIML,85,90,88,92,Yes
1,102,DIYA,21.0,Female,CSE,78,85,82,88,Yes
2,103,ROHAN,20.0,Male,AIML,92,95,94,96,Yes
3,104,ANANYA,21.0,Female,ISE,67,72,70,75,No
4,105,KARAN,22.0,Male,CSE,74,68,76,82,No

In [81]:
df["Math"].value_counts()

85    1
78    1
92    1
67    1
74    1
88    1
59    1
95    1
81    1
73    1
Name: Math, dtype: int64

In [82]:
df["Age"].unique()

array([20., 21., 22.])

In [83]:
df["Age"].nunique()

3

In [84]:
df.groupby("Gender")["Math"].mean()

Gender
Female    80.2
Male      78.2
Name: Math, dtype: float64

In [85]:
df.groupby("Gender")["Math"].agg(["max","min","mean"])

        max  min  mean
Gender
Female   95   67  80.2
Male     92   59  78.2

In [90]:
df1 = pd.Series(["a", "b"])
df2 = pd.Series(["c", "d"])

pd.concat([df1, df2])

0    a
1    b
0    c
1    d
dtype: object

In [93]:
df.rename(columns={"Age":"Student_Age"})

,Student_ID,Name,Student_Age,Gender,Department,Math,Python,AI,Attendance,Placement
0,101,AARAV,20.0,Male,AIML,85,90,88,92,Yes
1,102,DIYA,21.0,Female,CSE,78,85,82,88,Yes
2,103,ROHAN,20.0,Male,AIML,92,95,94,96,Yes
3,104,ANANYA,21.0,Female,ISE,67,72,70,75,No
4,105,KARAN,22.0,Male,CSE,74,68,76,82,No
5,106,MEERA,20.0,Female,AIML,88,91,90,94,Yes
6,107,ADITYA,21.0,Male,ISE,59,65,62,70,No
7,108,SNEHA,22.0,Female,CSE,95,93,97,98,Yes
8,109,RAHUL,20.0,Male,AIML,81,79,85,89,Yes
9,110,PRIYA,21.0,Female,ISE,73,77,71,80,No